foreground #eae0e7
background #161217

cursor #e7b6f0
cursor_text_color #462151

selection_foreground #462151
selection_background #e7b6f0

color0 #161217
color1 #ffb4ab
color2 #e7b6f0
color3 #f5b7b2
color4 #e7b6f0
color5 #d6c0d6
color6 #f5b7b2
color7 #eae0e7

color8 #988e97
color9 #ffb4ab
color10 #e7b6f0
color11 #f5b7b2
color12 #e7b6f0
color13 #d6c0d6
color14 #f5b7b2
color15 #eae0e7
