#!/bin/bash

WALLPAPER_DIR="$HOME/wallpapers"

SELECTED=$(find "$WALLPAPER_DIR" -type f \
    \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) |
    while read -r file; do
        echo -en "$(basename "$file")\0icon\x1f$file\n"
    done |
    rofi -dmenu \
        -i \
        -p "Wallpaper" \
        -config "$HOME/.config/rofi/wallpaper.rasi")

[ -z "$SELECTED" ] && exit 0

# Recupera o caminho completo pelo nome escolhido
SELECTED=$(find "$WALLPAPER_DIR" -type f -name "$SELECTED" -print -quit)

[ -z "$SELECTED" ] && exit 0

feh --bg-fill "$SELECTED"
wal -i "$SELECTED" -n
i3-msg reload
