#############################################
# PICOM — i3 / X11
#############################################

#############################################
# BACKEND / PERFORMANCE
#############################################

backend = "glx";

vsync = true;

use-damage = true;

no-frame-pacing = false;

dithered-present = true;

unredir-if-possible = true;

unredir-if-possible-delay = 0;



rules = (

    # =====================================
    # ROFI
    # =====================================

    {
        match = "class_i = 'rofi'";

        animations = (
            {
                triggers = [ "open" ];

                preset = "slide-in";
                direction = "down";
                duration = 0.2;
            },
            {
                triggers = [ "close" ];

                preset = "slide-out";
                direction = "down";
                duration = 0.2
            }
            
        );
    },

    # =====================================
    # POLYBAR
    # =====================================
    {
        match = "name = 'polybar-top'";

        animations = (
            {
                triggers = [ "open", "show" ];

                preset = "slide-in";
                direction = "up";
                duration = 0.25;
            },
            {
                triggers = [ "close", "hide" ];

                preset = "slide-out";
                direction = "up";
                duration = 0.25;
            }
        );
    },
    {
        match = "name = 'polybar-bottom'";

        animations = (
            {
                triggers = [ "open", "show" ];

                preset = "slide-in";
                direction = "down";
                duration = 0.25;
            },
            {
                triggers = [ "close", "hide" ];

                preset = "slide-out";
                direction = "up";
                duration = 0.25;
            }
        );
    },

);



animations = (

    # Abrir janela → bounce
    {
        triggers = [ "open" ];

        offset-y = {
            duration = 0.45;
            start = 80;
            end = 0;
            curve = "cubic-bezier(0.34, 1.56, 0.64, 1)";
        };
    },

    # Fechar janela → disappear
    {
        triggers = [ "close" ];

        preset = "disappear";
        duration = 0.25;
    },

    # Trocar de workspace → fade in
    {
        triggers = [ "show" ];

        offset-y = {
            duration = 0.45;
            start = 80;
            end = 0;
            curve = "cubic-bezier(0.34, 1.56, 0.64, 1)";
        };
    },

    # Redimensionar/mover → geometry
    {
        triggers = [ "geometry" ];

        preset = "geometry-change";
        duration = 0.25;
    }
);
