--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/renan/wallpapers/manga.png"

-- Special
background="#121518"
foreground="#cbe6f0"
cursor="#cbe6f0"

-- Colors
color0="#121518"
color1="#B2A35C"
color2="#5D7083"
color3="#B1739C"
color4="#68B6C5"
color5="#DA96AF"
color6="#C5A5BC"
color7="#cbe6f0"
color8="#8ea1a8"
color9="#B2A35C"
color10="#5D7083"
color11="#B1739C"
color12="#68B6C5"
color13="#DA96AF"
color14="#C5A5BC"
color15="#cbe6f0"
