# Shell variables
# Generated by 'wal'
wallpaper='/home/renan/wallpapers/manga.png'

# Special
background='#121518'
foreground='#cbe6f0'
cursor='#cbe6f0'

# Colors
color0='#121518'
color1='#B2A35C'
color2='#5D7083'
color3='#B1739C'
color4='#68B6C5'
color5='#DA96AF'
color6='#C5A5BC'
color7='#cbe6f0'
color8='#8ea1a8'
color9='#B2A35C'
color10='#5D7083'
color11='#B1739C'
color12='#68B6C5'
color13='#DA96AF'
color14='#C5A5BC'
color15='#cbe6f0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
