foreground   #cbe6f0
background   #121518
cursor       #cbe6f0

color0       #121518
color8       #8ea1a8
color1       #B2A35C
color9       #B2A35C
color2       #5D7083
color10      #5D7083
color3       #B1739C
color11      #B1739C
color4       #68B6C5
color12      #68B6C5
color5       #DA96AF
color13      #DA96AF
color6       #C5A5BC
color14      #C5A5BC
color7       #cbe6f0
color15      #cbe6f0
