include-file = ~/.cache/wal/colors-polybar.ini

;   Polybar configuration
;   Top bar + Bottom bar
;   CPU + GPU + RAM + MPD

; ==========================================
; COLORS
; ==========================================


; ==========================================
; TOP BAR
; ==========================================

[bar/top]
width = 100%
height = 15pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 0pt
border-color = #ffffff

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = Adwaita Mono:size=10;2

modules-left = date
modules-center =
modules-right = xworkspaces

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


; ==========================================
; BOTTOM BAR
; ==========================================

[bar/bottom]
width = 100%
height = 15pt
radius = 0

bottom = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 0pt
border-color = #ffffff

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = Adwaita Mono:size=10;2

modules-left = cpu gpu memory
modules-center = mpd
modules-right =

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


; ==========================================
; WORKSPACES
; ==========================================

[module/xworkspaces]
type = internal/xworkspaces

label-active =  %name%
label-active-foreground = ${colors.background}
label-active-background = ${colors.foreground}
label-active-underline = ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1


; ==========================================
; CPU
; ==========================================

[module/cpu]
type = internal/cpu

interval = 2

format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}

label = %percentage:2%%


; ==========================================
; GPU
; NVIDIA
; ==========================================

[module/gpu]
type = custom/script

exec = nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits
interval = 2

format-prefix = "GPU "
format-prefix-foreground = ${colors.primary}

label = %output%%


; ==========================================
; RAM
; ==========================================

[module/memory]
type = internal/memory

interval = 2

format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}

label = %percentage_used:2%%


; ==========================================
; MPD
; ==========================================

[module/mpd]
type = internal/mpd

interval = 1

host = 127.0.0.1
port = 6600

format-online = <label-song>
format-offline = MPD offline
format-offline-foreground = ${colors.disabled}

format-playing = <label-song>
format-playing-prefix = "▶ "
format-playing-prefix-foreground = ${colors.primary}

format-paused = <label-song>
format-paused-prefix = "⏸ "
format-paused-prefix-foreground = ${colors.primary}

format-stopped = MPD stopped
format-stopped-prefix = "■ "
format-stopped-prefix-foreground = ${colors.primary}
format-stopped-foreground = ${colors.disabled}

label-song = %title% - %artist%
label-song-maxlen = 60
label-song-ellipsis = ...


; ==========================================
; DATE
; ==========================================

[module/date]
type = custom/script

exec = LC_TIME=en_US.UTF-8 date '+%H:%M %a, %d de %B'

interval = 1

label = %output%
label-foreground = ${colors.primary}


; ==========================================
; PULSEAUDIO
; ==========================================

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}

format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}


; ==========================================
; SYSTEM SETTINGS
; ==========================================

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
